//! Unique identifiers for entities and edges.
//!
//! This module provides type-safe identifiers for graph nodes ([`EntityId`])
//! and relationships ([`EdgeId`]).
//!
//! # Example
//!
//! ```
//! use manifoldb_core::types::{EntityId, EdgeId};
//!
//! // Create identifiers
//! let user_id = EntityId::new(1);
//! let edge_id = EdgeId::new(100);
//!
//! // Convert to raw values for storage/serialization
//! assert_eq!(user_id.as_u64(), 1);
//! assert_eq!(edge_id.as_u64(), 100);
//!
//! // IDs are ordered and hashable
//! let id1 = EntityId::new(1);
//! let id2 = EntityId::new(2);
//! assert!(id1 < id2);
//! ```

use std::fmt;

use serde::{Deserialize, Serialize};

/// Unique identifier for an entity (node) in the graph.
///
/// `EntityId` wraps a `u64` and provides type safety to prevent accidentally
/// using an entity ID where an edge ID is expected (or vice versa).
///
/// IDs are typically auto-generated by the database when creating entities
/// via [`DatabaseTransaction::create_entity`], but can also be created manually
/// for bulk loading scenarios.
///
/// # Example
///
/// ```
/// use manifoldb_core::EntityId;
///
/// let id = EntityId::new(42);
/// assert_eq!(id.as_u64(), 42);
/// println!("{}", id); // Prints: EntityId(42)
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct EntityId(u64);

impl EntityId {
    /// Create a new `EntityId` from a raw u64 value.
    #[inline]
    #[must_use]
    pub const fn new(id: u64) -> Self {
        Self(id)
    }

    /// Get the raw u64 value.
    #[inline]
    #[must_use]
    pub const fn as_u64(self) -> u64 {
        self.0
    }
}

impl From<u64> for EntityId {
    #[inline]
    fn from(id: u64) -> Self {
        Self::new(id)
    }
}

impl fmt::Display for EntityId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "EntityId({})", self.0)
    }
}

/// Unique identifier for an edge (relationship) in the graph.
///
/// `EdgeId` wraps a `u64` and provides type safety to prevent accidentally
/// using an edge ID where an entity ID is expected (or vice versa).
///
/// IDs are typically auto-generated by the database when creating edges
/// via [`DatabaseTransaction::create_edge`], but can also be created manually
/// for bulk loading scenarios.
///
/// # Example
///
/// ```
/// use manifoldb_core::EdgeId;
///
/// let id = EdgeId::new(100);
/// assert_eq!(id.as_u64(), 100);
/// println!("{}", id); // Prints: EdgeId(100)
/// ```
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord, Serialize, Deserialize)]
pub struct EdgeId(u64);

impl EdgeId {
    /// Create a new `EdgeId` from a raw u64 value.
    #[inline]
    #[must_use]
    pub const fn new(id: u64) -> Self {
        Self(id)
    }

    /// Get the raw u64 value.
    #[inline]
    #[must_use]
    pub const fn as_u64(self) -> u64 {
        self.0
    }
}

impl From<u64> for EdgeId {
    #[inline]
    fn from(id: u64) -> Self {
        Self::new(id)
    }
}

impl fmt::Display for EdgeId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "EdgeId({})", self.0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn entity_id_roundtrip() {
        let id = EntityId::new(42);
        assert_eq!(id.as_u64(), 42);
    }

    #[test]
    fn edge_id_roundtrip() {
        let id = EdgeId::new(123);
        assert_eq!(id.as_u64(), 123);
    }

    #[test]
    fn ids_are_ordered() {
        let a = EntityId::new(1);
        let b = EntityId::new(2);
        assert!(a < b);
    }
}
